tap "homebrew/bundle"
tap "homebrew/services"
tap "instrumenta/instrumenta"
tap "raggi/ale"

brew "antidote"
brew "autojump"
brew "awscli"
brew "bat"
brew "bufbuild/buf/buf"
brew "direnv"
brew "dive"
brew "findutils"
brew "fzf"
brew "gh"
brew "gnu-sed"
brew "gnupg"
brew "jsonnet-bundler"
brew "jump"
brew "derailed/k9s/k9s"
brew "libpq"
brew "mas"
brew "md5sha1sum"
brew "mtr"
brew "nmap"
brew "parallel"
brew "ripgrep"
brew "shellcheck"
brew "speedtest-cli"
brew "starship"
brew "stern"
brew "tmux"
brew "tree"
brew "yamllint"
brew "yarn"
brew "yj"
brew "watch"
brew "raggi/ale/openssl-osx-ca"

brew "warrensbox/tap/tfswitch"
brew "pre-commit"
brew "terraform-docs"
brew "tflint"
brew "minamijoyo/tfupdate/tfupdate"
brew "jq"

cask "flycut" unless system "find -f '/Applications/Flycut.app' > /dev/null"
cask "font-agave-nerd-font"
cask "ngrok"
cask "rectangle" unless system "find -f '/Applications/Rectangle.app' > /dev/null"
cask "stats"