#!/bin/bash
DEBUG=${DEBUG:-false}
ASDF_VERSION="${ASDF_VERSION:-v0.12.0}"

set -eo pipefail
[[ "${DEBUG}" == "true" ]] && set -x

if ! test -d "$HOME/.asdf"; then
    echo "Installing ASDF"
    git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch $ASDF_VERSION
fi

. "$HOME/.asdf/asdf.sh"

cat .tool-versions | awk '{ print $1 }' | xargs -I % sh -c 'asdf plugin add %'

asdf install
