#!/bin/bash
DEBUG=${DEBUG:-false}

set -o pipefail
[[ "${DEBUG}" == "true" ]] && set -x

plugins=$(cat .tool-versions | awk '{ print $1 }')
for p in $plugins; do
    asdf plugin add "$p"
done

asdf install
