#!/bin/bash
DEBUG=${DEBUG:-false}
ASDF_VERSION="${ASDF_VERSION:-v0.12.0}"

set -o pipefail
[[ "${DEBUG}" == "true" ]] && set -x

if ! test -d "$HOME/.asdf"; then
    echo "Installing ASDF"
    git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch $ASDF_VERSION
fi

. "$HOME/.asdf/asdf.sh"

plugins=$(cat .tool-versions | awk '{ print $1 }')
for p in $plugins; do
    asdf plugin add "$p"
done

asdf install
