#!/bin/bash
DEBUG=${DEBUG:-false}

set -eo pipefail
[[ "${DEBUG}" == "true" ]] && set -x

if which kubectl > /dev/null 2>&1 && which krew > /dev/null 2>&1; then
    echo "Installing krew plugins"
    DEBUG=${DEBUG} krew install < "$(pwd)/krew-plugins.txt"
else
    echo "Missing kubectl and/or krew -- please run make asdf_install"
fi
